# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'GyMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GyMate
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
